services:

  # --------------------------------
  # Nuxt Application
  # --------------------------------
  web:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: surakshit-ai-web

    ports:
      - "3000:3000"

    environment:
      NODE_ENV: production
      HOST: 0.0.0.0
      PORT: 3000
      ML_SERVICE_URL: http://ml-service:8000

    depends_on:
      - ml-service


  # --------------------------------
  # Python ML Service
  # --------------------------------
  ml-service:
    build:
      context: ./ml-service
      dockerfile: Dockerfile

    container_name: surakshit-ai-ml

    ports:
      - "8000:8000"